DEFAULT_PEOPLECODE_SQL = """
SELECT
    OBJECTID1,
    OBJECTVALUE1,
    OBJECTID2,
    OBJECTVALUE2,
    OBJECTID3,
    OBJECTVALUE3,
    OBJECTID4,
    OBJECTVALUE4,
    OBJECTID5,
    OBJECTVALUE5,
    OBJECTID6,
    OBJECTVALUE6,
    OBJECTID7,
    OBJECTVALUE7,
    PROGSEQ,
    PCTEXT
FROM PSPCMTXT
WHERE PCTEXT IS NOT NULL
ORDER BY
    OBJECTVALUE1,
    OBJECTVALUE2,
    OBJECTVALUE3,
    PROGSEQ
"""
